//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication1.Service2Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service2Reference.Service2")]
    public interface Service2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service2/DoWork", ReplyAction="http://tempuri.org/Service2/DoWorkResponse")]
        int DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service2/DoWork", ReplyAction="http://tempuri.org/Service2/DoWorkResponse")]
        System.Threading.Tasks.Task<int> DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service2Channel : TestWebApplication1.Service2Reference.Service2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<TestWebApplication1.Service2Reference.Service2>, TestWebApplication1.Service2Reference.Service2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<int> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
